server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: route_service
          uri: http://localhost:8081
          predicates:
            - Path=/routes/**

        - id: vehicle_service
          uri: http://localhost:8082
          predicates:
            - Path=/vehicles/**

        - id: schedule_service
          uri: http://localhost:8083
          predicates:
            - Path=/schedules/**