server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: route_service
          container_name: route_service
#          uri: "http://localhost:8081"
          uri: "http://route_service:8081"
          predicates:
            - Path=/routes/**

        - id: vehicle_service
#          uri: "http://localhost:8082"
          uri: "http://vehicle_service:8082"
          predicates:
            - Path=/vehicles/**

        - id: schedule_service
#          uri: "http://localhost:8083"
          uri: "http://schedule_service:8083"
          predicates:
            - Path=/schedules/**

management:
  endpoints:
    web:
      exposure:
        include: "*"