#services:
#
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
#
#  route_service:
#    build: ./route_service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - redis
#
#  vehicle_service:
#    build: ./vehicle_service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - redis
#
#  schedule_service:
#    build: ./schedule_service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - redis
#      - route_service
#
#  gateway_service:
#    build: ./gateway_service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - route_service
#      - vehicle_service
#      - schedule_service

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - urban-network

  route_service:
    build: ./route_service
    container_name: route_service
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - vehicle_service
    networks:
      - urban-network

  vehicle_service:
    build: ./vehicle_service
    container_name: vehicle_service
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - urban-network

  schedule_service:
    build: ./schedule_service
    container_name: schedule_service
    ports:
      - "8083:8083"
    depends_on:
      - redis
      - route_service
    networks:
      - urban-network

  gateway_service:
    build: ./gateway_service
    container_name: gateway_service
    ports:
      - "8080:8080"
    depends_on:
      - route_service
      - vehicle_service
      - schedule_service
    networks:
      - urban-network

networks:
  urban-network:
    driver: bridge

